//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.App.Resources.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.App.Resources.Labels.LabelStrings", typeof(LabelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartment.
        /// </summary>
        public static string Adresse_Appartement {
            get {
                return ResourceManager.GetString("Adresse_Appartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string Adresse_CodePostal {
            get {
                return ResourceManager.GetString("Adresse_CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street number.
        /// </summary>
        public static string Adresse_NoCivique {
            get {
                return ResourceManager.GetString("Adresse_NoCivique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street name.
        /// </summary>
        public static string Adresse_Rue {
            get {
                return ResourceManager.GetString("Adresse_Rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Adresse_Ville {
            get {
                return ResourceManager.GetString("Adresse_Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Antecedents_Description {
            get {
                return ResourceManager.GetString("Antecedents_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the medical condition.
        /// </summary>
        public static string Antecedents_Description_Placeholder {
            get {
                return ResourceManager.GetString("Antecedents_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Antecedents_Public {
            get {
                return ResourceManager.GetString("Antecedents_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Antecedents_Type {
            get {
                return ResourceManager.GetString("Antecedents_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the medical condition type.
        /// </summary>
        public static string Antecedents_Type_Placeholder {
            get {
                return ResourceManager.GetString("Antecedents_Type_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Commanditaire_Adresse {
            get {
                return ResourceManager.GetString("Commanditaire_Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Commanditaire_Commentaire {
            get {
                return ResourceManager.GetString("Commanditaire_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Commanditaire_Contact {
            get {
                return ResourceManager.GetString("Commanditaire_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-specified.
        /// </summary>
        public static string Commanditaire_DefaultValue {
            get {
                return ResourceManager.GetString("Commanditaire_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Commanditaire_Nom {
            get {
                return ResourceManager.GetString("Commanditaire_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Commanditaire_TypeCommanditaire {
            get {
                return ResourceManager.GetString("Commanditaire_TypeCommanditaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Contact_Courriel {
            get {
                return ResourceManager.GetString("Contact_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Contact_Nom {
            get {
                return ResourceManager.GetString("Contact_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Contact_Prenom {
            get {
                return ResourceManager.GetString("Contact_Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Contact_Telephone {
            get {
                return ResourceManager.GetString("Contact_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Contact_Type {
            get {
                return ResourceManager.GetString("Contact_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Formations_Description {
            get {
                return ResourceManager.GetString("Formations_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the training.
        /// </summary>
        public static string Formations_Description_Placeholder {
            get {
                return ResourceManager.GetString("Formations_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Formations_Public {
            get {
                return ResourceManager.GetString("Formations_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Formations_Titre {
            get {
                return ResourceManager.GetString("Formations_Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the training.
        /// </summary>
        public static string Formations_Titre_Placeholder {
            get {
                return ResourceManager.GetString("Formations_Titre_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Fournisseurs_Commentaire {
            get {
                return ResourceManager.GetString("Fournisseurs_Commentaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Fournisseurs_Nom {
            get {
                return ResourceManager.GetString("Fournisseurs_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Fournisseurs_Type {
            get {
                return ResourceManager.GetString("Fournisseurs_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Code.
        /// </summary>
        public static string Login_CodeUniversel {
            get {
                return ResourceManager.GetString("Login_CodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Universal Code.
        /// </summary>
        public static string Login_CodeUniversel_Placeholder {
            get {
                return ResourceManager.GetString("Login_CodeUniversel_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_MotDePasse {
            get {
                return ResourceManager.GetString("Login_MotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password.
        /// </summary>
        public static string Login_MotDePasse_Placeholder {
            get {
                return ResourceManager.GetString("Login_MotDePasse_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-specified.
        /// </summary>
        public static string Profil_DefaultValue {
            get {
                return ResourceManager.GetString("Profil_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Code.
        /// </summary>
        public static string ProfilAvance_CodePermanent {
            get {
                return ResourceManager.GetString("ProfilAvance_CodePermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Permanent Code.
        /// </summary>
        public static string ProfilAvance_CodePermanent_Placeholder {
            get {
                return ResourceManager.GetString("ProfilAvance_CodePermanent_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ProfilAvance_Courriel {
            get {
                return ResourceManager.GetString("ProfilAvance_Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email (This is not necessarily your ÉTS email).
        /// </summary>
        public static string ProfilAvance_Courriel_Placeholder {
            get {
                return ResourceManager.GetString("ProfilAvance_Courriel_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string ProfilAvance_DateNaissance {
            get {
                return ResourceManager.GetString("ProfilAvance_DateNaissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Public.
        /// </summary>
        public static string ProfilAvance_Public {
            get {
                return ResourceManager.GetString("ProfilAvance_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ProfilAvance_Telephone {
            get {
                return ResourceManager.GetString("ProfilAvance_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number (10 digits).
        /// </summary>
        public static string ProfilAvance_Telephone_Placeholder {
            get {
                return ResourceManager.GetString("ProfilAvance_Telephone_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string ProfilBase_Avatar {
            get {
                return ResourceManager.GetString("ProfilBase_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string ProfilBase_Concentration {
            get {
                return ResourceManager.GetString("ProfilBase_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your program.
        /// </summary>
        public static string ProfilBase_Concentration_Placeholder {
            get {
                return ResourceManager.GetString("ProfilBase_Concentration_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ProfilBase_Nom {
            get {
                return ResourceManager.GetString("ProfilBase_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Last Name.
        /// </summary>
        public static string ProfilBase_Nom_Placeholder {
            get {
                return ResourceManager.GetString("ProfilBase_Nom_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ProfilBase_Prenom {
            get {
                return ResourceManager.GetString("ProfilBase_Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First Name.
        /// </summary>
        public static string ProfilBase_Prenom_Placeholder {
            get {
                return ResourceManager.GetString("ProfilBase_Prenom_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Public.
        /// </summary>
        public static string ProfilBase_Public {
            get {
                return ResourceManager.GetString("ProfilBase_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by.
        /// </summary>
        public static string RestException_Cause {
            get {
                return ResourceManager.GetString("RestException_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services Error.
        /// </summary>
        public static string RestException_Prefix {
            get {
                return ResourceManager.GetString("RestException_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services Validation Mismatch.
        /// </summary>
        public static string RestException_Validation_Prefix {
            get {
                return ResourceManager.GetString("RestException_Validation_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Téléphone {
            get {
                return ResourceManager.GetString("Téléphone", resourceCulture);
            }
        }
    }
}
