<?xml version="1.0" encoding="utf-8"?><Database Name="SIMPLETS" Class="SecurityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="security.Claims" Member="Claims">
    <Type Name="Claim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="security.RolesTemplates" Member="RoleTemplates">
    <Type Name="RoleTemplate">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="RoleTemplate_RoleTemplateModuleClaims" Member="RoleTemplateModuleClaims" ThisKey="Id" OtherKey="RoleTemplateId" Type="RoleTemplateModuleClaims" />
    </Type>
  </Table>
  <Table Name="security.Contexts" Member="Contexts">
    <Type Name="Context">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Context_PrincipalModuleContextClaims" Member="PrincipalModuleContextClaims" ThisKey="Id" OtherKey="ContextId" Type="PrincipalModuleContextClaims" />
    </Type>
  </Table>
  <Table Name="security.Modules" Member="Modules">
    <Type Name="Module">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Module_PrincipalModuleContextClaims" Member="PrincipalModuleContextClaims" ThisKey="Id" OtherKey="ModuleId" Type="PrincipalModuleContextClaims" />
      <Association Name="Module_RoleTemplateModuleClaims" Member="RoleTemplateModuleClaims" ThisKey="Id" OtherKey="ModuleId" Type="RoleTemplateModuleClaims" />
    </Type>
  </Table>
  <Table Name="security.Principals" Member="Principals">
    <Type Name="Principal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Identity]" Member="Identity" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="Principal_PrincipalAudit" Member="PrincipalAudits" ThisKey="Id" OtherKey="PrincipalId" Type="PrincipalAudit" />
      <Association Name="Principal_PrincipalModuleContextClaims" Member="PrincipalModuleContextClaims" ThisKey="Id" OtherKey="PrincipalId" Type="PrincipalModuleContextClaims" />
    </Type>
  </Table>
  <Table Name="security.PrincipalsAudits" Member="PrincipalAudits">
    <Type Name="PrincipalAudit">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PrincipalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IpAddress" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Principal_PrincipalAudit" Member="Principal" ThisKey="PrincipalId" OtherKey="Id" Type="Principal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="security.PrincipalsModulesContextsClaims" Member="PrincipalModuleContextClaims">
    <Type Name="PrincipalModuleContextClaims">
      <Column Name="PrincipalId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ContextId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Claims" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Context_PrincipalModuleContextClaims" Member="Context" ThisKey="ContextId" OtherKey="Id" Type="Context" IsForeignKey="true" />
      <Association Name="Principal_PrincipalModuleContextClaims" Member="Principal" ThisKey="PrincipalId" OtherKey="Id" Type="Principal" IsForeignKey="true" />
      <Association Name="Module_PrincipalModuleContextClaims" Member="Module" ThisKey="ModuleId" OtherKey="Id" Type="Module" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="security.RolesTemplatesModulesClaims" Member="RoleTemplateModuleClaims">
    <Type Name="RoleTemplateModuleClaims">
      <Column Name="RoleTemplateId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Claims" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Module_RoleTemplateModuleClaims" Member="Module" ThisKey="ModuleId" OtherKey="Id" Type="Module" IsForeignKey="true" />
      <Association Name="RoleTemplate_RoleTemplateModuleClaims" Member="RoleTemplate" ThisKey="RoleTemplateId" OtherKey="Id" Type="RoleTemplate" IsForeignKey="true" />
    </Type>
  </Table>
</Database>