//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.Core.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.Core.Resources.Exceptions.ExceptionStrings", typeof(ExceptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type {0} cannot be found..
        /// </summary>
        internal static string Core_Exceptions_Repository_EntityNotFound_Name {
            get {
                return ResourceManager.GetString("Core_Exceptions_Repository_EntityNotFound_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity of type {0} with id {1} cannot be found..
        /// </summary>
        internal static string Core_Exceptions_Repository_EntityNotFound_NameAndId {
            get {
                return ResourceManager.GetString("Core_Exceptions_Repository_EntityNotFound_NameAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity is not unique. Where clause must point to a unique entity..
        /// </summary>
        internal static string Core_Exceptions_Repository_EntityNotUnique {
            get {
                return ResourceManager.GetString("Core_Exceptions_Repository_EntityNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to access non-configured contexts. Default is unauthorized..
        /// </summary>
        internal static string Core_Exceptions_Security_ContextsDoNotAllExist {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_ContextsDoNotAllExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact kerberos server. If you&apos;re not in the application domain, make sure you are connected through a vpn..
        /// </summary>
        internal static string Core_Exceptions_Security_KerberosDown {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_KerberosDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to access non-configured module. Default is unauthorized..
        /// </summary>
        internal static string Core_Exceptions_Security_ModuleDoesNotExist {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_ModuleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal has no authorization in the system. Create the principal before attempting again..
        /// </summary>
        internal static string Core_Exceptions_Security_PrincipalDoesNotExist {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_PrincipalDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The principal does not have the required claims to act on this module in these contexts..
        /// </summary>
        internal static string Core_Exceptions_Security_PrincipalModuleContextsClaimsInsufficient {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_PrincipalModuleContextsClaimsInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action cannot be authorized..
        /// </summary>
        internal static string Core_Exceptions_Security_Unauthorized {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The principal have no right to access this module in these contexts..
        /// </summary>
        internal static string Core_Exceptions_Security_UnauthorizedModuleContextsAccess {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_UnauthorizedModuleContextsAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given credentials does not exist..
        /// </summary>
        internal static string Core_Exceptions_Security_WrongCredentials {
            get {
                return ResourceManager.GetString("Core_Exceptions_Security_WrongCredentials", resourceCulture);
            }
        }
    }
}
