//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.Services.Resources.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized Strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContractStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.Services.Resources.Contracts.ContractStrings", typeof(ContractStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubAdministrationService_CreateClub_EnsuresPositiveClubId {
            get {
                return ResourceManager.GetString("ClubAdministrationService_CreateClub_EnsuresPositiveClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubAdministrationService_CreateClub_RequiresClub {
            get {
                return ResourceManager.GetString("ClubAdministrationService_CreateClub_RequiresClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditaireService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Create_RequiresCommanditaire {
            get {
                return ResourceManager.GetString("CommanditaireService_Create_RequiresCommanditaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditaireService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Get_EnsuresNonNullCommanditaire {
            get {
                return ResourceManager.GetString("CommanditaireService_Get_EnsuresNonNullCommanditaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Get_EnsuresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditaireService_Get_EnsuresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditaireService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Get_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditaireService_Get_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_GetAll_EnsuresNonNullCommanditaires {
            get {
                return ResourceManager.GetString("CommanditaireService_GetAll_EnsuresNonNullCommanditaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditaireService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("CommanditaireService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditaireService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Update_RequiresCommanditaire {
            get {
                return ResourceManager.GetString("CommanditaireService_Update_RequiresCommanditaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireService_Update_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditaireService_Update_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A club name is required to create a sponsor..
        /// </summary>
        internal static String CommanditeService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditeService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A sponsor entity is required to create a sponsor..
        /// </summary>
        internal static String CommanditeService_Create_RequiresCommandite {
            get {
                return ResourceManager.GetString("CommanditeService_Create_RequiresCommandite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Create_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditeService_Create_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A club name is required to delete a sponsor..
        /// </summary>
        internal static String CommanditeService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditeService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Delete_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditeService_Delete_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A positive sponsor id is required to delete a sponsor..
        /// </summary>
        internal static String CommanditeService_Delete_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("CommanditeService_Delete_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Get_EnsuresNonNullCommandite {
            get {
                return ResourceManager.GetString("CommanditeService_Get_EnsuresNonNullCommandite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Get_EnsuresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("CommanditeService_Get_EnsuresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A club name is required to get a sponsor..
        /// </summary>
        internal static String CommanditeService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditeService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Get_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditeService_Get_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A positive sponsor id is required to get a sponsor..
        /// </summary>
        internal static String CommanditeService_Get_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("CommanditeService_Get_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_GetAll_EnsuresNonNullCommandites {
            get {
                return ResourceManager.GetString("CommanditeService_GetAll_EnsuresNonNullCommandites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A club name is requried to get its sponsors..
        /// </summary>
        internal static String CommanditeService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditeService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_GetAll_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditeService_GetAll_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("CommanditeService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_GetClubsSubscribedTo_EnsuresNonNullClubs {
            get {
                return ResourceManager.GetString("CommanditeService_GetClubsSubscribedTo_EnsuresNonNullClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A club name is required to update one of its sponsor..
        /// </summary>
        internal static String CommanditeService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("CommanditeService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A sponsor entity is required to update a sponsor..
        /// </summary>
        internal static String CommanditeService_Update_RequiresCommandite {
            get {
                return ResourceManager.GetString("CommanditeService_Update_RequiresCommandite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeService_Update_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("CommanditeService_Update_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A positive sponsor id is required to update a sponsor..
        /// </summary>
        internal static String CommanditeService_Update_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("CommanditeService_Update_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A context is required to bind a role to a user..
        /// </summary>
        internal static String ContextAdministrationService_BindRoleToPrincipal_RequiresContext {
            get {
                return ResourceManager.GetString("ContextAdministrationService_BindRoleToPrincipal_RequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A user name is required to bind a role to a user..
        /// </summary>
        internal static String ContextAdministrationService_BindRoleToPrincipal_RequiresIdentity {
            get {
                return ResourceManager.GetString("ContextAdministrationService_BindRoleToPrincipal_RequiresIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A role is required to bind a role to a user..
        /// </summary>
        internal static String ContextAdministrationService_BindRoleToPrincipal_RequiresRole {
            get {
                return ResourceManager.GetString("ContextAdministrationService_BindRoleToPrincipal_RequiresRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContextAdministrationService_CreateContext_EnsuresPositiveContextId {
            get {
                return ResourceManager.GetString("ContextAdministrationService_CreateContext_EnsuresPositiveContextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A context is required to create a context..
        /// </summary>
        internal static String ContextAdministrationService_CreateContext_RequiresContext {
            get {
                return ResourceManager.GetString("ContextAdministrationService_CreateContext_RequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContextAdministrationService_GetAllClaimsOnContext_EnsuresNonNullClaimsByModule {
            get {
                return ResourceManager.GetString("ContextAdministrationService_GetAllClaimsOnContext_EnsuresNonNullClaimsByModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContextAdministrationService_GetAllClaimsOnContext_RequiresContext {
            get {
                return ResourceManager.GetString("ContextAdministrationService_GetAllClaimsOnContext_RequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContextAdministrationService_GetAllClaimsOnContext_RequiresOwner {
            get {
                return ResourceManager.GetString("ContextAdministrationService_GetAllClaimsOnContext_RequiresOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A context is required to remove a user&apos;s claims..
        /// </summary>
        internal static String ContextAdministrationService_RemoveAllClaimsFromPrincipal_RequiresContext {
            get {
                return ResourceManager.GetString("ContextAdministrationService_RemoveAllClaimsFromPrincipal_RequiresContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A user name is required to remove a user&apos;s claims..
        /// </summary>
        internal static String ContextAdministrationService_RemoveAllClaimsFromPrincipal_RequiresIdentity {
            get {
                return ResourceManager.GetString("ContextAdministrationService_RemoveAllClaimsFromPrincipal_RequiresIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String DescriptionService_DescribeApiEntities_EnsuresNonNullEntityDescriptions {
            get {
                return ResourceManager.GetString("DescriptionService_DescribeApiEntities_EnsuresNonNullEntityDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String DescriptionService_DescribeApiMethods_EnsuresNonNullModuleDescription {
            get {
                return ResourceManager.GetString("DescriptionService_DescribeApiMethods_EnsuresNonNullModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EnumerationService_GetAllConcentrations_EnsuresNonNullConcentrations {
            get {
                return ResourceManager.GetString("EnumerationService_GetAllConcentrations_EnsuresNonNullConcentrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EnumerationService_GetAllStatutsSuivie_EnsuresNonNullStatusSuivie {
            get {
                return ResourceManager.GetString("EnumerationService_GetAllStatutsSuivie_EnsuresNonNullStatusSuivie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EnumerationService_GetAllTypesContacts_EnsuresNonNullTypesContact {
            get {
                return ResourceManager.GetString("EnumerationService_GetAllTypesContacts_EnsuresNonNullTypesContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EnumerationService_GetAllUnites_EnsuresNonNullUnites {
            get {
                return ResourceManager.GetString("EnumerationService_GetAllUnites_EnsuresNonNullUnites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Create_EnsuresPositiveFournisseurId {
            get {
                return ResourceManager.GetString("FournisseurService_Create_EnsuresPositiveFournisseurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("FournisseurService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Create_RequiresFournisseur {
            get {
                return ResourceManager.GetString("FournisseurService_Create_RequiresFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("FournisseurService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Delete_RequiresPositiveFournisseurId {
            get {
                return ResourceManager.GetString("FournisseurService_Delete_RequiresPositiveFournisseurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Get_EnsuresNonNullFournisseur {
            get {
                return ResourceManager.GetString("FournisseurService_Get_EnsuresNonNullFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("FournisseurService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Get_RequiresPositiveFournisseurId {
            get {
                return ResourceManager.GetString("FournisseurService_Get_RequiresPositiveFournisseurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_GetAll_EnsuresNonNullFournisseurs {
            get {
                return ResourceManager.GetString("FournisseurService_GetAll_EnsuresNonNullFournisseurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("FournisseurService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("FournisseurService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("FournisseurService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Update_RequiresFournisseur {
            get {
                return ResourceManager.GetString("FournisseurService_Update_RequiresFournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurService_Update_RequiresPositiveFournisseurId {
            get {
                return ResourceManager.GetString("FournisseurService_Update_RequiresPositiveFournisseurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InscriptionService_SubscribeToClub_RequiresClubName {
            get {
                return ResourceManager.GetString("InscriptionService_SubscribeToClub_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InscriptionService_SubscribeToClub_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("InscriptionService_SubscribeToClub_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InscriptionService_UnsubscribeFromClub_RequiresClubName {
            get {
                return ResourceManager.GetString("InscriptionService_UnsubscribeFromClub_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InscriptionService_UnsubscribeFromClub_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("InscriptionService_UnsubscribeFromClub_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("InventaireService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Create_RequiresItem {
            get {
                return ResourceManager.GetString("InventaireService_Create_RequiresItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("InventaireService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Delete_RequiresPositiveItemId {
            get {
                return ResourceManager.GetString("InventaireService_Delete_RequiresPositiveItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Get_EnsuresNonNullItem {
            get {
                return ResourceManager.GetString("InventaireService_Get_EnsuresNonNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Get_EnsuresPositiveItemId {
            get {
                return ResourceManager.GetString("InventaireService_Get_EnsuresPositiveItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("InventaireService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Get_RequiresPositiveItemId {
            get {
                return ResourceManager.GetString("InventaireService_Get_RequiresPositiveItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_GetAll_EnsuresNonNullItems {
            get {
                return ResourceManager.GetString("InventaireService_GetAll_EnsuresNonNullItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("InventaireService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("InventaireService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("InventaireService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Update_RequiresItem {
            get {
                return ResourceManager.GetString("InventaireService_Update_RequiresItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String InventaireService_Update_RequiresPositiveItemId {
            get {
                return ResourceManager.GetString("InventaireService_Update_RequiresPositiveItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("MeetingService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Create_RequiresMeeting {
            get {
                return ResourceManager.GetString("MeetingService_Create_RequiresMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("MeetingService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Delete_RequiresPositiveCommanditaireId {
            get {
                return ResourceManager.GetString("MeetingService_Delete_RequiresPositiveCommanditaireId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Delete_RequiresPositiveMeetingId {
            get {
                return ResourceManager.GetString("MeetingService_Delete_RequiresPositiveMeetingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Get_EnsuresNonNullMeeting {
            get {
                return ResourceManager.GetString("MeetingService_Get_EnsuresNonNullMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Get_EnsuresPositiveMeetingId {
            get {
                return ResourceManager.GetString("MeetingService_Get_EnsuresPositiveMeetingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("MeetingService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Get_RequiresPositiveMeetingId {
            get {
                return ResourceManager.GetString("MeetingService_Get_RequiresPositiveMeetingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_GetAll_EnsuresNonNullMeetings {
            get {
                return ResourceManager.GetString("MeetingService_GetAll_EnsuresNonNullMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("MeetingService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("MeetingService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("MeetingService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Update_RequiresMeeting {
            get {
                return ResourceManager.GetString("MeetingService_Update_RequiresMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingService_Update_RequiresPositiveMeetingId {
            get {
                return ResourceManager.GetString("MeetingService_Update_RequiresPositiveMeetingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String PrincipalAdministrationService_CreatePrincipal_EnsuresPositivePrincipalId {
            get {
                return ResourceManager.GetString("PrincipalAdministrationService_CreatePrincipal_EnsuresPositivePrincipalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A user name is required to create a user..
        /// </summary>
        internal static String PrincipalAdministrationService_CreatePrincipal_RequiresIdentity {
            get {
                return ResourceManager.GetString("PrincipalAdministrationService_CreatePrincipal_RequiresIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to A user name is required to know whether it exists..
        /// </summary>
        internal static String PrincipalAdministrationService_PrincipalExists_RequiresIdentity {
            get {
                return ResourceManager.GetString("PrincipalAdministrationService_PrincipalExists_RequiresIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAdministrationService_CreateBaseProfil_EnsuresPositiveProfilId {
            get {
                return ResourceManager.GetString("ProfilAdministrationService_CreateBaseProfil_EnsuresPositiveProfilId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAdministrationService_CreateBaseProfil_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("ProfilAdministrationService_CreateBaseProfil_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilService_Get_EnsuresNonNullProfil {
            get {
                return ResourceManager.GetString("ProfilService_Get_EnsuresNonNullProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilService_Get_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("ProfilService_Get_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilService_GetClubsSubscribedTo_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("ProfilService_GetClubsSubscribedTo_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilService_Update_RequiresCodeUniversel {
            get {
                return ResourceManager.GetString("ProfilService_Update_RequiresCodeUniversel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilService_Update_RequiresProfil {
            get {
                return ResourceManager.GetString("ProfilService_Update_RequiresProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Create_EnsuresPositiveSuivieId {
            get {
                return ResourceManager.GetString("SuivieService_Create_EnsuresPositiveSuivieId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Create_RequiresClubName {
            get {
                return ResourceManager.GetString("SuivieService_Create_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Create_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("SuivieService_Create_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Create_RequiresSuivie {
            get {
                return ResourceManager.GetString("SuivieService_Create_RequiresSuivie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Delete_RequiresClubName {
            get {
                return ResourceManager.GetString("SuivieService_Delete_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Delete_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("SuivieService_Delete_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Delete_RequiresPositiveSuivieId {
            get {
                return ResourceManager.GetString("SuivieService_Delete_RequiresPositiveSuivieId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Get_EnsuresNonNullSuivie {
            get {
                return ResourceManager.GetString("SuivieService_Get_EnsuresNonNullSuivie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Get_RequiresClubName {
            get {
                return ResourceManager.GetString("SuivieService_Get_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Get_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("SuivieService_Get_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Get_RequiresPositiveSuivieId {
            get {
                return ResourceManager.GetString("SuivieService_Get_RequiresPositiveSuivieId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_GetAll_EnsuresNonNullSuivies {
            get {
                return ResourceManager.GetString("SuivieService_GetAll_EnsuresNonNullSuivies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_GetAll_RequiresClubName {
            get {
                return ResourceManager.GetString("SuivieService_GetAll_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_GetAll_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("SuivieService_GetAll_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_GetAll_RequiresUndefinedOrPositiveTake {
            get {
                return ResourceManager.GetString("SuivieService_GetAll_RequiresUndefinedOrPositiveTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Update_RequiresClubName {
            get {
                return ResourceManager.GetString("SuivieService_Update_RequiresClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Update_RequiresPositiveCommanditeId {
            get {
                return ResourceManager.GetString("SuivieService_Update_RequiresPositiveCommanditeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Update_RequiresPositiveSuivieId {
            get {
                return ResourceManager.GetString("SuivieService_Update_RequiresPositiveSuivieId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieService_Update_RequiresSuivie {
            get {
                return ResourceManager.GetString("SuivieService_Update_RequiresSuivie", resourceCulture);
            }
        }
    }
}
