//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.Services.Resources.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized Strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.Services.Resources.Validation.ValidationStrings", typeof(ValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_Appartement_StringLength {
            get {
                return ResourceManager.GetString("AdresseDto_Appartement_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_CodePostal_Required {
            get {
                return ResourceManager.GetString("AdresseDto_CodePostal_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_CodePostal_StringLength {
            get {
                return ResourceManager.GetString("AdresseDto_CodePostal_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_NoCivique_Range {
            get {
                return ResourceManager.GetString("AdresseDto_NoCivique_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_NoCivique_Required {
            get {
                return ResourceManager.GetString("AdresseDto_NoCivique_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_Rue_Required {
            get {
                return ResourceManager.GetString("AdresseDto_Rue_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_Rue_StringLength {
            get {
                return ResourceManager.GetString("AdresseDto_Rue_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_Ville_Required {
            get {
                return ResourceManager.GetString("AdresseDto_Ville_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AdresseDto_Ville_StringLength {
            get {
                return ResourceManager.GetString("AdresseDto_Ville_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AntecedentDto_Description_Required {
            get {
                return ResourceManager.GetString("AntecedentDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AntecedentDto_Description_StringLength {
            get {
                return ResourceManager.GetString("AntecedentDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AntecedentDto_Nom_Required {
            get {
                return ResourceManager.GetString("AntecedentDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AntecedentDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("AntecedentDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String AntecedentDto_Public_Required {
            get {
                return ResourceManager.GetString("AntecedentDto_Public_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubDto_Description_Required {
            get {
                return ResourceManager.GetString("ClubDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubDto_Description_StringLength {
            get {
                return ResourceManager.GetString("ClubDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubDto_Nom_Required {
            get {
                return ResourceManager.GetString("ClubDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ClubDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("ClubDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_Adresse_Required {
            get {
                return ResourceManager.GetString("CommanditaireDto_Adresse_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_Commentaire_StringLength {
            get {
                return ResourceManager.GetString("CommanditaireDto_Commentaire_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_Contact_Required {
            get {
                return ResourceManager.GetString("CommanditaireDto_Contact_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_Nom_Required {
            get {
                return ResourceManager.GetString("CommanditaireDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("CommanditaireDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_TypeCommanditaireId_Range {
            get {
                return ResourceManager.GetString("CommanditaireDto_TypeCommanditaireId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditaireDto_TypeCommanditaireId_Required {
            get {
                return ResourceManager.GetString("CommanditaireDto_TypeCommanditaireId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_Commentaire_StringLength {
            get {
                return ResourceManager.GetString("CommanditeDto_Commentaire_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_Recu_Required {
            get {
                return ResourceManager.GetString("CommanditeDto_Recu_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_Suivies_Required {
            get {
                return ResourceManager.GetString("CommanditeDto_Suivies_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_TypeCommanditeId_Range {
            get {
                return ResourceManager.GetString("CommanditeDto_TypeCommanditeId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_TypeCommanditeId_Required {
            get {
                return ResourceManager.GetString("CommanditeDto_TypeCommanditeId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_Valeur_Range {
            get {
                return ResourceManager.GetString("CommanditeDto_Valeur_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String CommanditeDto_Valeur_Required {
            get {
                return ResourceManager.GetString("CommanditeDto_Valeur_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ConcentrationDto_Acronyme_Required {
            get {
                return ResourceManager.GetString("ConcentrationDto_Acronyme_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ConcentrationDto_Acronyme_StringLength {
            get {
                return ResourceManager.GetString("ConcentrationDto_Acronyme_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ConcentrationDto_Description_Required {
            get {
                return ResourceManager.GetString("ConcentrationDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ConcentrationDto_Description_StringLength {
            get {
                return ResourceManager.GetString("ConcentrationDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Courriel_Regex {
            get {
                return ResourceManager.GetString("ContactDto_Courriel_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Courriel_StringLength {
            get {
                return ResourceManager.GetString("ContactDto_Courriel_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Nom_Required {
            get {
                return ResourceManager.GetString("ContactDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("ContactDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Prenom_Required {
            get {
                return ResourceManager.GetString("ContactDto_Prenom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Prenom_StringLength {
            get {
                return ResourceManager.GetString("ContactDto_Prenom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_Telephone_Regex {
            get {
                return ResourceManager.GetString("ContactDto_Telephone_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_TypeContactId_Range {
            get {
                return ResourceManager.GetString("ContactDto_TypeContactId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ContactDto_TypeContactId_Required {
            get {
                return ResourceManager.GetString("ContactDto_TypeContactId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_DateDebut_Required {
            get {
                return ResourceManager.GetString("EvenementDto_DateDebut_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_DateFin_Required {
            get {
                return ResourceManager.GetString("EvenementDto_DateFin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_Description_Required {
            get {
                return ResourceManager.GetString("EvenementDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_Description_StringLength {
            get {
                return ResourceManager.GetString("EvenementDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_Nom_Required {
            get {
                return ResourceManager.GetString("EvenementDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String EvenementDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("EvenementDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FormationDto_Description_Required {
            get {
                return ResourceManager.GetString("FormationDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FormationDto_Description_StringLength {
            get {
                return ResourceManager.GetString("FormationDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FormationDto_Public_Required {
            get {
                return ResourceManager.GetString("FormationDto_Public_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FormationDto_Titre_Required {
            get {
                return ResourceManager.GetString("FormationDto_Titre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FormationDto_Titre_StringLength {
            get {
                return ResourceManager.GetString("FormationDto_Titre_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_Adresse_Required {
            get {
                return ResourceManager.GetString("FournisseurDto_Adresse_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_Contact_Required {
            get {
                return ResourceManager.GetString("FournisseurDto_Contact_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_Nom_Required {
            get {
                return ResourceManager.GetString("FournisseurDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("FournisseurDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_TypeFournisseurId_Range {
            get {
                return ResourceManager.GetString("FournisseurDto_TypeFournisseurId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String FournisseurDto_TypeFournisseurId_Required {
            get {
                return ResourceManager.GetString("FournisseurDto_TypeFournisseurId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String GroupeDto_Description_Required {
            get {
                return ResourceManager.GetString("GroupeDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String GroupeDto_Description_StringLength {
            get {
                return ResourceManager.GetString("GroupeDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String GroupeDto_Nom_Required {
            get {
                return ResourceManager.GetString("GroupeDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String GroupeDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("GroupeDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_Code_StringLength {
            get {
                return ResourceManager.GetString("ItemDto_Code_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_Description_Required {
            get {
                return ResourceManager.GetString("ItemDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_Description_StringLength {
            get {
                return ResourceManager.GetString("ItemDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_Quantite_Range {
            get {
                return ResourceManager.GetString("ItemDto_Quantite_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_Quantite_Required {
            get {
                return ResourceManager.GetString("ItemDto_Quantite_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_QuantiteMax_Range {
            get {
                return ResourceManager.GetString("ItemDto_QuantiteMax_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_QuantiteMin_Range {
            get {
                return ResourceManager.GetString("ItemDto_QuantiteMin_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_UniteId_Range {
            get {
                return ResourceManager.GetString("ItemDto_UniteId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ItemDto_UniteId_Required {
            get {
                return ResourceManager.GetString("ItemDto_UniteId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingDto_Commentaire_Required {
            get {
                return ResourceManager.GetString("MeetingDto_Commentaire_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingDto_Commentaire_StringLength {
            get {
                return ResourceManager.GetString("MeetingDto_Commentaire_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingDto_ConvocateurId_Range {
            get {
                return ResourceManager.GetString("MeetingDto_ConvocateurId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingDto_DateDebut_Required {
            get {
                return ResourceManager.GetString("MeetingDto_DateDebut_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MeetingDto_DateFin_Required {
            get {
                return ResourceManager.GetString("MeetingDto_DateFin_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MembreDto_Actif_Required {
            get {
                return ResourceManager.GetString("MembreDto_Actif_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MembreDto_DateDebut_Required {
            get {
                return ResourceManager.GetString("MembreDto_DateDebut_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MembreDto_Titre_Required {
            get {
                return ResourceManager.GetString("MembreDto_Titre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String MembreDto_Titre_StringLength {
            get {
                return ResourceManager.GetString("MembreDto_Titre_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String PreferenceDto_Name_Required {
            get {
                return ResourceManager.GetString("PreferenceDto_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String PreferenceDto_Name_StringLength {
            get {
                return ResourceManager.GetString("PreferenceDto_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String PreferenceDto_Value_Required {
            get {
                return ResourceManager.GetString("PreferenceDto_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String PreferenceDto_Value_StringLength {
            get {
                return ResourceManager.GetString("PreferenceDto_Value_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAvanceDto_CodePermament_StringLength {
            get {
                return ResourceManager.GetString("ProfilAvanceDto_CodePermament_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAvanceDto_Courriel_Regex {
            get {
                return ResourceManager.GetString("ProfilAvanceDto_Courriel_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAvanceDto_Courriel_StringLength {
            get {
                return ResourceManager.GetString("ProfilAvanceDto_Courriel_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAvanceDto_Public_Required {
            get {
                return ResourceManager.GetString("ProfilAvanceDto_Public_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilAvanceDto_Telephone_Regex {
            get {
                return ResourceManager.GetString("ProfilAvanceDto_Telephone_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Actif_Required {
            get {
                return ResourceManager.GetString("ProfilDto_Actif_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_ConcentrationId_Range {
            get {
                return ResourceManager.GetString("ProfilDto_ConcentrationId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Nom_Required {
            get {
                return ResourceManager.GetString("ProfilDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("ProfilDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Prenom_Required {
            get {
                return ResourceManager.GetString("ProfilDto_Prenom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Prenom_StringLength {
            get {
                return ResourceManager.GetString("ProfilDto_Prenom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_ProfilAvance_Required {
            get {
                return ResourceManager.GetString("ProfilDto_ProfilAvance_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String ProfilDto_Public_Required {
            get {
                return ResourceManager.GetString("ProfilDto_Public_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String StatutSuivieDto_Code_Required {
            get {
                return ResourceManager.GetString("StatutSuivieDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String StatutSuivieDto_Code_StringLength {
            get {
                return ResourceManager.GetString("StatutSuivieDto_Code_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String StatutSuivieDto_Description_Required {
            get {
                return ResourceManager.GetString("StatutSuivieDto_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String StatutSuivieDto_Description_StringLength {
            get {
                return ResourceManager.GetString("StatutSuivieDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_Commentaire_Required {
            get {
                return ResourceManager.GetString("SuivieDto_Commentaire_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_Commentaire_StringLength {
            get {
                return ResourceManager.GetString("SuivieDto_Commentaire_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_DateSuivie_Required {
            get {
                return ResourceManager.GetString("SuivieDto_DateSuivie_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_MembreId_Range {
            get {
                return ResourceManager.GetString("SuivieDto_MembreId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_MembreId_Required {
            get {
                return ResourceManager.GetString("SuivieDto_MembreId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_StatutSuivieId_Range {
            get {
                return ResourceManager.GetString("SuivieDto_StatutSuivieId_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String SuivieDto_StatutSuivieId_Required {
            get {
                return ResourceManager.GetString("SuivieDto_StatutSuivieId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeAntecedentDto_Description_StringLength {
            get {
                return ResourceManager.GetString("TypeAntecedentDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeAntecedentDto_Nom_Required {
            get {
                return ResourceManager.GetString("TypeAntecedentDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeAntecedentDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("TypeAntecedentDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditaireDto_Description_StringLength {
            get {
                return ResourceManager.GetString("TypeCommanditaireDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditaireDto_Nom_Required {
            get {
                return ResourceManager.GetString("TypeCommanditaireDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditaireDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("TypeCommanditaireDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditeDto_Description_StringLength {
            get {
                return ResourceManager.GetString("TypeCommanditeDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditeDto_Nom_Required {
            get {
                return ResourceManager.GetString("TypeCommanditeDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeCommanditeDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("TypeCommanditeDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeContactDto_Description_StringLength {
            get {
                return ResourceManager.GetString("TypeContactDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeContactDto_Nom_Required {
            get {
                return ResourceManager.GetString("TypeContactDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeContactDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("TypeContactDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeFournisseurDto_Description_StringLength {
            get {
                return ResourceManager.GetString("TypeFournisseurDto_Description_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeFournisseurDto_Nom_Required {
            get {
                return ResourceManager.GetString("TypeFournisseurDto_Nom_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String TypeFournisseurDto_Nom_StringLength {
            get {
                return ResourceManager.GetString("TypeFournisseurDto_Nom_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String UniteDto_Code_Required {
            get {
                return ResourceManager.GetString("UniteDto_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String UniteDto_Code_StringLength {
            get {
                return ResourceManager.GetString("UniteDto_Code_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String UniteDto_Systeme_Required {
            get {
                return ResourceManager.GetString("UniteDto_Systeme_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized String similar to .
        /// </summary>
        internal static String UniteDto_Systeme_StringLength {
            get {
                return ResourceManager.GetString("UniteDto_Systeme_StringLength", resourceCulture);
            }
        }
    }
}
