//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.App.Resources.Titles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TitleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TitleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.App.Resources.Titles.TitleStrings", typeof(TitleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Adresse_MainTitle {
            get {
                return ResourceManager.GetString("Adresse_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Medical History.
        /// </summary>
        public static string Antecedents_MainTitle {
            get {
                return ResourceManager.GetString("Antecedents_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplets Api Description.
        /// </summary>
        public static string ApiDescription_MainTitle {
            get {
                return ResourceManager.GetString("ApiDescription_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application_MainTitle {
            get {
                return ResourceManager.GetString("Application_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sponsor.
        /// </summary>
        public static string Commanditaire_MainTitle {
            get {
                return ResourceManager.GetString("Commanditaire_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Sponsors.
        /// </summary>
        public static string Commanditaires_MainTitle {
            get {
                return ResourceManager.GetString("Commanditaires_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_MainTitle {
            get {
                return ResourceManager.GetString("Contact_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplets Entities Description.
        /// </summary>
        public static string EntitiesDescription_MainTitle {
            get {
                return ResourceManager.GetString("EntitiesDescription_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your profile information*.
        /// </summary>
        public static string FirstLoginProfileEdition_MainTitle {
            get {
                return ResourceManager.GetString("FirstLoginProfileEdition_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Training.
        /// </summary>
        public static string Formations_MainTitle {
            get {
                return ResourceManager.GetString("Formations_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers List.
        /// </summary>
        public static string Fournisseurs_MainTitle {
            get {
                return ResourceManager.GetString("Fournisseurs_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in *.
        /// </summary>
        public static string Login_MainTitle {
            get {
                return ResourceManager.GetString("Login_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member List.
        /// </summary>
        public static string Membre_MainTitle {
            get {
                return ResourceManager.GetString("Membre_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Preferences.
        /// </summary>
        public static string Preferences_MainTitle {
            get {
                return ResourceManager.GetString("Preferences_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string Profil_MainTitle {
            get {
                return ResourceManager.GetString("Profil_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Advanced Profile.
        /// </summary>
        public static string ProfilAvance_MainTitle {
            get {
                return ResourceManager.GetString("ProfilAvance_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Base Profile.
        /// </summary>
        public static string ProfilBase_MainTitle {
            get {
                return ResourceManager.GetString("ProfilBase_MainTitle", resourceCulture);
            }
        }
    }
}
