//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sporacid.Simplets.Webapp.Core.Resources.Contracts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContractStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sporacid.Simplets.Webapp.Core.Resources.Contracts.ContractStrings", typeof(ContractStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationModule_Authenticate_EnsuresNonNullPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationModule_Authenticate_EnsuresNonNullPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationModule_Authenticate_EnsuresNonNullToken {
            get {
                return ResourceManager.GetString("AuthenticationModule_Authenticate_EnsuresNonNullToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationModule_Authenticate_EnsuresNonNullTokenAndPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationModule_Authenticate_EnsuresNonNullTokenAndPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationModule_Authenticate_RequiresCredentials {
            get {
                return ResourceManager.GetString("AuthenticationModule_Authenticate_RequiresCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationModule_Authenticate_RequiresIdentity {
            get {
                return ResourceManager.GetString("AuthenticationModule_Authenticate_RequiresIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObservable_AddObserver_RequiresObserver {
            get {
                return ResourceManager.GetString("AuthenticationObservable_AddObserver_RequiresObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObservable_NotifyAuthentication_RequiresPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationObservable_NotifyAuthentication_RequiresPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObservable_NotifyAuthentication_RequiresToken {
            get {
                return ResourceManager.GetString("AuthenticationObservable_NotifyAuthentication_RequiresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObservable_NotifyAuthentication_RequiresTokenAndPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationObservable_NotifyAuthentication_RequiresTokenAndPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObservable_RemoveObserver_RequiresObserver {
            get {
                return ResourceManager.GetString("AuthenticationObservable_RemoveObserver_RequiresObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObserver_Update_RequiresPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationObserver_Update_RequiresPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObserver_Update_RequiresToken {
            get {
                return ResourceManager.GetString("AuthenticationObserver_Update_RequiresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthenticationObserver_Update_RequiresTokenAndPrincipal {
            get {
                return ResourceManager.GetString("AuthenticationObserver_Update_RequiresTokenAndPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthorizationModule_Authorize_RequiresContexts {
            get {
                return ResourceManager.GetString("AuthorizationModule_Authorize_RequiresContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthorizationModule_Authorize_RequiresModule {
            get {
                return ResourceManager.GetString("AuthorizationModule_Authorize_RequiresModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AuthorizationModule_Authorize_RequiresPrincipal {
            get {
                return ResourceManager.GetString("AuthorizationModule_Authorize_RequiresPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LdapSearcher_SearchForUser_EnsuresNonNullLdapUser {
            get {
                return ResourceManager.GetString("LdapSearcher_SearchForUser_EnsuresNonNullLdapUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LdapSearcher_SearchForUser_RequiresValue {
            get {
                return ResourceManager.GetString("LdapSearcher_SearchForUser_RequiresValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Add_RequiresEntity {
            get {
                return ResourceManager.GetString("Repository_Add_RequiresEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_AddAll_RequiresEntities {
            get {
                return ResourceManager.GetString("Repository_AddAll_RequiresEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Delete_RequiresEntity {
            get {
                return ResourceManager.GetString("Repository_Delete_RequiresEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Delete_RequiresEntityId {
            get {
                return ResourceManager.GetString("Repository_Delete_RequiresEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_DeleteAll_RequiresWhereClause {
            get {
                return ResourceManager.GetString("Repository_DeleteAll_RequiresWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Get_EnsuresNonNullEntity {
            get {
                return ResourceManager.GetString("Repository_Get_EnsuresNonNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Get_RequiresEntityId {
            get {
                return ResourceManager.GetString("Repository_Get_RequiresEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_GetAll_EnsuresNonNullEntities {
            get {
                return ResourceManager.GetString("Repository_GetAll_EnsuresNonNullEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_GetAll_RequiresWhereClause {
            get {
                return ResourceManager.GetString("Repository_GetAll_RequiresWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_GetUnique_EnsuresNonNullEntity {
            get {
                return ResourceManager.GetString("Repository_GetUnique_EnsuresNonNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_GetUnique_RequiresWhereClause {
            get {
                return ResourceManager.GetString("Repository_GetUnique_RequiresWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Has_RequiresEntity {
            get {
                return ResourceManager.GetString("Repository_Has_RequiresEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Has_RequiresEntityId {
            get {
                return ResourceManager.GetString("Repository_Has_RequiresEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Has_RequiresWhereClause {
            get {
                return ResourceManager.GetString("Repository_Has_RequiresWhereClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_Update_RequiresEntity {
            get {
                return ResourceManager.GetString("Repository_Update_RequiresEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Repository_UpdateAll_RequiresEntities {
            get {
                return ResourceManager.GetString("Repository_UpdateAll_RequiresEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoleBootstrapper_BindClaims_EnsuresNonNullRoleBootstrapper {
            get {
                return ResourceManager.GetString("RoleBootstrapper_BindClaims_EnsuresNonNullRoleBootstrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoleBootstrapper_BootstrapTo_RequiresRole {
            get {
                return ResourceManager.GetString("RoleBootstrapper_BootstrapTo_RequiresRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoleBootstrapper_ToModules_EnsuresNonNullRoleBootstrapper {
            get {
                return ResourceManager.GetString("RoleBootstrapper_ToModules_EnsuresNonNullRoleBootstrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RoleBootstrapper_ToModules_RequiresModules {
            get {
                return ResourceManager.GetString("RoleBootstrapper_ToModules_RequiresModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SecurityDatabaseBootstrapper_Bootstrap_RequiresAssembly {
            get {
                return ResourceManager.GetString("SecurityDatabaseBootstrapper_Bootstrap_RequiresAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SecurityDatabaseBootstrapper_Bootstrap_RequiresEndpointNamespaces {
            get {
                return ResourceManager.GetString("SecurityDatabaseBootstrapper_Bootstrap_RequiresEndpointNamespaces", resourceCulture);
            }
        }
    }
}
